[package]
name = "projet-robert"
version = "1.1.0"
authors = ["Julien Garderon <julien.garderon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
